nginx:
  image: nginx:alpine
  ports:
    - "10081:80"
  volumes:
    - ./data/site.conf:/etc/nginx/conf.d/default.conf
    - ./data/site:/usr/share/nginx/html
  links:
    - php

php:
  image: php:5.6.40-fpm-alpine-mysqli
  volumes:
    - ./data/site:/usr/share/nginx/html
  links:
    - mysql

mysql:
  image: mysql:5.7.30
  volumes:
    - ./data/db:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: "##xxabce"
    MYSQL_DATABASE:      "cms"
    MYSQL_USER:          "cms"
    MYSQL_PASSWORD:      "##xxabcc"
